services:
  sveltekit:
    container_name: my-app               # 컨테이너 이름을 지정
    build:
      context: .
      dockerfile: Dockerfile
    ports:
      - "5173:5173"                     # 포트 맵핑
    volumes:
      - .:/app                          # 로컬 파일 시스템을 컨테이너에 마운트 (소스 코드 수정 시 자동 반영)
      - /app/node_modules               # node_modules는 가져가지 않음.
    # environment:
    #  - NODE_ENV=development           # 개발 환경 설정 안해도 됨.
    # command: ["npm", "run", "dev"]    # 개발 모드로 실행 안해도 됨.
    environment:
      - CHOKIDAR_USEPOLLING=true  # 개발옵션
      - CHOKIDAR_INTERVAL=1000   # 개발 옵션(옵션) 폴링 간격(ms). 기본은 100ms
    restart: always               # 프로그램 자동 재시작 정책